### ISSUE TITLE
BOM is incomplete

### ISSUE THREAD

**Issue by DasPez** [vattern/holiot-carrier#2]
The BOM in PRODUCTIONFILES is missing a lot of parts

https://github.com/vattern/holiot-carrier/blob/2ea75663381d650d06d59db998a7086e5ef48cf4/PCB/PRODUCTION_FILES/BOM-adapter-holyiot.csv

**Comment by vattern** [comment]
I've added the bom.xls JLC has for the last order. Please verify it before ordering.
